### PR TITLE
Pin exact SUNDIALS version to resolve incompatibilities

### PR DESCRIPTION
**Pull request by speth**
Resolves Cantera/cantera#1645.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bryanwweber** [comment]
Thanks @speth. There's a couple other places with the 6.6 pin for the other sub packages, I think those need to be updated too

**Comment by speth** [comment]
Oh, good point. Thanks, @bryanwweber.

**Comment by bryanwweber** [comment]
Thanks @speth, I'll wait for the CI to finish and then merge. On a totally unrelated note, I see that we're adding options to tune the optimizer: [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=826043&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5) but that depends on the CPU which may be different from the user's CPU (for example, AMD instead of Intel Xeon). Should we drop those tuning parameters here?

**Comment by speth** [comment]
> Thanks @speth, I'll wait for the CI to finish and then merge. On a totally unrelated note, I see that we're adding options to tune the optimizer: [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=826043&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5) but that depends on the CPU which may be different from the user's CPU (for example, AMD instead of Intel Xeon). Should we drop those tuning parameters here?

Our build scripts are just passing through the value of the `CFLAGS` environment variable. I assume that is being set by  the conda forge pipeline, and isn't something we should mess with.

**Pull request merged**
