### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by speth**
The purpose of this is to trigger a rebuild due to transient upload failures from the previous build attempt.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by bryanwweber — APPROVED** [review]

**Comment by matthiasdiener** [comment]
If it is a transient build error, it can be easier just to restart the build (via e.g. https://github.com/conda-forge/cantera-feedstock/runs/34619482093, I hope others are able to access the re-run build option there as well) without creating a new build number.

**Comment by bryanwweber** [comment]
Neither Ray nor I have the ability to do that, it requires a login as far as I know 😕

**Comment by matthiasdiener** [comment]
Huh, that's strange. When you access (e.g.) https://github.com/conda-forge/cantera-feedstock/runs/34627443271 , is there no 'Re-run' button on the left after each failing test, like in the screenshot? That's what I use to rerun on an intermittent failure. 

image

**Comment by bryanwweber** [comment]
Thanks @matthiasdiener! I learned something today, and also triggered that build again :sweat: :joy:

**Pull request merged**
