### PR TITLE
Bump to v2.5.0

### PR DESCRIPTION
**Pull request by bryanwweber**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by inducer** [comment]
@conda-forge-admin, please rerender

**Comment by bryanwweber** [comment]
Thanks @inducer! But why is the macOS package failing :cry:

**Comment by inducer** [comment]
```
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/cantera-recipe_1612562746729/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.9/site-packages/cantera/_cantera.cpython-39-darwin.so, 2): Library not loaded: build/lib/libcantera.2.5.0.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/cantera-recipe_1612562746729/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.9/site-packages/cantera/_cantera.cpython-39-darwin.so
  Reason: image not found
```

Whereas in some places it seems to build `build/lib/libcantera.2.5.0rc1.dylib`.

**Comment by bryanwweber** [comment]
Thanks @inducer That seems to be resolved by bumping to the final release. Any idea about the problems on Travis with the PPC builds? It looks like there's so much output that the pipe can't handle it? But maybe that's just concealing the actual error message?

**Comment by bryanwweber** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
It sure does look like the output is truncated after
```
The install/build script(s) for libcantera deleted the following files (from dependencies) from the prefix:
```
I'm guessing that's conda-build complaining that files were deleted. Maybe we can be a bit more selective in our deleting? Only delete files that have cantera somewhere in the path?

**Comment by inducer** [comment]
> make conda-build complain less

Thx!

**Comment by bryanwweber** [comment]
Thanks @isuruf! @inducer any other changes to make here? Can you "Approve" when it looks good?

**Review by inducer — APPROVED** [review]

**Pull request merged**
