### PR TITLE
exact pinning

### LINKED ISSUE #46: Possibility of installing incompatible versions of `cantera` / `libcantera`
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

It seems that the version dependencies between the different cantera packages are not strict enough. There are situations where conda installs package versions that are not compatible.

This is an example on linux-64. The conflict is likely due to some hwloc version incompatibility:

```console
$ conda create -n cantera-test
$ conda activate cantera-test
$ conda install python=3.12 cantera 'pocl<6' gmsh  # Somewhat contrived example, but there are likely other ways that trigger this issue
[...]
libhwloc           conda-forge/linux-64::libhwloc-2.10.0-default_h5622ce7_1001
cantera            conda-forge/linux-64::cantera-3.0.1-py312h3524396_10
libcantera         conda-forge/linux-64::libcantera-3.0.1-h6436c1b_9
[...]

$ python -c 'import cantera'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/shared/home/mdiener/Work/e12/miniforge3/envs/can-test/lib/python3.12/site-packages/cantera/__init__.py", line 4, in <module>
    from ._cantera import *
  File "build/python/cantera/_cantera.pyx", line 33, in init cantera._cantera
  File "build/python/cantera/_utils.pyx", line 66, in init cantera._utils
ImportError: Mismatch between Cantera Python module Git commit (cfeb901) and Cantera shared library git commit (e271cdc)
```

```
### Installed packages

# packages in environment at /shared/home/mdiener/Work/e12/miniforge3/envs/can-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohappyeyeballs          2.4.3              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.10         py312h178313f_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
cantera                   3.0.1           py312h3524396_10    conda-forge
cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
double-conversion         3.3.0                h59595ed_0    conda-forge
eigen                     3.4.0                h00ab1b0_0    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
ffmpeg                    6.1.2           gpl_h3e00e3c_103    conda-forge
fltk                      1.3.9                h9305793_1    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeimage                 3.18.0              h3a85593_22    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.5.0           py312h66e93f0_0    conda-forge
gl2ps                     1.4.2                hae5d5c5_1    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmsh                      4.13.1               hccb25f3_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imath                     3.1.12               h7955e40_0    conda-forge
jsoncpp                   1.9.5                h4bd325d_1    conda-forge
jxrlib                    1.1                  hd590300_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libass                    0.17.3               h1dc1e6a_0    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libcantera                3.0.1                h6436c1b_9    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h127d8a8_5    conda-forge
libclang-cpp19.1          19.1.2          default_hb5137d0_1    conda-forge
libclang13                19.1.2          default_h9c6a7e4_1    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libdrm                    2.4.123              hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libegl                    1.7.0                ha4b6fd6_1    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgl                     1.7.0                ha4b6fd6_1    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libglu                    9.0.0             ha6d2627_1004    conda-forge
libglvnd                  1.7.0                ha4b6fd6_1    conda-forge
libglx                    1.7.0                ha4b6fd6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libhwloc                  2.10.0          default_h5622ce7_1001    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libllvm19                 19.1.2               ha7bfdaf_0    conda-forge
libllvmspirv15            15.0.5               h629725b_0    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libogg                    1.3.5                h4ab18f5_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_0    conda-forge
libopenvino               2024.3.0             h2da1b83_0    conda-forge
libopenvino-auto-batch-plugin 2024.3.0             hb045406_0    conda-forge
libopenvino-auto-plugin   2024.3.0             hb045406_0    conda-forge
libopenvino-hetero-plugin 2024.3.0             h5c03a75_0    conda-forge
libopenvino-intel-cpu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-intel-gpu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-intel-npu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-ir-frontend   2024.3.0             h5c03a75_0    conda-forge
libopenvino-onnx-frontend 2024.3.0             h07e8aee_0    conda-forge
libopenvino-paddle-frontend 2024.3.0             h07e8aee_0    conda-forge
libopenvino-pytorch-frontend 2024.3.0             he02047a_0    conda-forge
libopenvino-tensorflow-frontend 2024.3.0             h39126c6_0    conda-forge
libopenvino-tensorflow-lite-frontend 2024.3.0             he02047a_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     17.0                 h04577a9_4    conda-forge
libprotobuf               4.25.3               hd5b35b9_1    conda-forge
libraw                    0.21.3               hca62329_0    conda-forge
libsqlite                 3.47.0               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtheora                 1.1.1             h4ab18f5_1006    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.22.0               h8a09558_1    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.14.1               hac33072_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h2c5496b_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzip                    1.11.1               hf83b1b0_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
llvm-spirv-15             15.0.5               h629725b_0    conda-forge
loguru                    0.7.2           py312h7900ff3_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
metis                     5.1.0             hd0bcaf9_1007    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
msgpack-python            1.1.0           py312h68727a3_0    conda-forge
multidict                 6.1.0           py312h178313f_1    conda-forge
mysql-common              9.0.1                h266115a_2    conda-forge
mysql-libs                9.0.1                he0572af_2    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nlohmann_json             3.11.3               he02047a_1    conda-forge
numpy                     2.1.2           py312h58c1407_0    conda-forge
occt                      7.8.1           all_h4c4714a_203    conda-forge
ocl-icd                   2.3.2                hd590300_1    conda-forge
openexr                   3.3.1                hccdc605_2    conda-forge
openh264                  2.4.1                h59595ed_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openldap                  2.6.8                hedd0468_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pocl                      5.0                  h3b55f2c_6    conda-forge
pocl-core                 5.0                  hbf9fd79_6    conda-forge
pocl-cpu                  5.0                  he8db0dd_6    conda-forge
pocl-cpu-minimal          5.0                  h9a9641c_6    conda-forge
pocl-cuda                 5.0                  hbf9fd79_6    conda-forge
pocl-remote               5.0                  h9a9641c_6    conda-forge
proj                      9.4.1                h54d7996_1    conda-forge
propcache                 0.2.0           py312h66e93f0_2    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pugixml                   1.14                 h59595ed_0    conda-forge
python                    3.12.7          hc5c86c4_0_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
qt6-main                  6.7.3                h6e8976b_1    conda-forge
rapidjson                 1.1.0.post20240409      hac33072_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
ruamel.yaml               0.18.6          py312h66e93f0_1    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
spirv-tools               2024.3               h84d6215_0    conda-forge
sqlite                    3.47.0               h9eae976_0    conda-forge
suitesparse               7.8.2                hb42a789_0    conda-forge
sundials                  7.1.1                ha52427a_0    conda-forge
svt-av1                   2.2.1                h5888daf_0    conda-forge
tbb                       2021.12.0            h297d8ca_1    conda-forge
tbb-devel                 2021.12.0            h7c56ddd_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
utfcpp                    4.0.5                ha770c72_0    conda-forge
vtk                       9.3.1           qt_py312hadc0db7_205    conda-forge
vtk-base                  9.3.1           qt_py312hb14dd37_205    conda-forge
vtk-io-ffmpeg             9.3.1           qt_py312hc8241c7_205    conda-forge
wayland                   1.23.1               h3e06ad9_0    conda-forge
wayland-protocols         1.37                 hd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wslink                    2.2.1              pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xcb-util                  0.4.1                hb711507_2    conda-forge
xcb-util-cursor           0.1.5                hb9d3cd8_0    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xkeyboard-config          2.43                 hb9d3cd8_0    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxcomposite        0.4.6                hb9d3cd8_2    conda-forge
xorg-libxcursor           1.2.2                hb9d3cd8_0    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.1                hb9d3cd8_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxmu               1.2.1                hb9d3cd8_1    conda-forge
xorg-libxrandr            1.5.4                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-libxt                1.3.0                hb9d3cd8_2    conda-forge
xorg-libxtst              1.2.5                hb9d3cd8_3    conda-forge
xorg-libxxf86vm           1.1.5                hb9d3cd8_4    conda-forge
xorg-xextproto            7.3.0             hb9d3cd8_1004    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
yarl                      1.16.0          py312h66e93f0_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

```
### Environment info


     active environment : can-test
    active env location : /shared/home/mdiener/Work/e12/miniforge3/envs/can-test
            shell level : 3
       user config file : /home/mdiener/.condarc
 populated config files : /shared/home/mdiener/Work/e12/miniforge3/.condarc
                          /home/mdiener/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=haswell
                          __conda=24.9.2=0
                          __cuda=12.2=0
                          __glibc=2.40=0
                          __linux=6.8.12=0
                          __unix=0=0
       base environment : /shared/home/mdiener/Work/e12/miniforge3  (writable)
      conda av data dir : /shared/home/mdiener/Work/e12/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /shared/home/mdiener/Work/e12/miniforge3/pkgs
                          /home/mdiener/.conda/pkgs
       envs directories : /shared/home/mdiener/Work/e12/miniforge3/envs
                          /home/mdiener/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.6 Linux/6.8.12-amd64 debian/n/a glibc/2.40 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 3098:3098
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by matthiasdiener**
Potentially fixes #46.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Review by bryanwweber — CHANGES_REQUESTED** [review]
Thanks @matthiasdiener. I think the only change is to bump the build number

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Comment by matthiasdiener** [comment]
> Thanks @matthiasdiener. I think the only change is to bump the build number

Good catch, thanks!

**Review by bryanwweber — APPROVED** [review]

**Comment by bryanwweber** [comment]
Uh oh, looks like this removed the Python 3.13 migration :disappointed: I'll try to work out what happened.

**Comment by matthiasdiener** [comment]
> Uh oh, looks like this removed the Python 3.13 migration 😞 I'll try to work out what happened.

Oh no... how strange. I suspect that in the first commit ([60ab82a](https://github.com/conda-forge/cantera-feedstock/pull/47/commits/60ab82af351b4873d0d36eedf31175703f8bb705)), rerendering removed the 3.13-related files (perhaps due to a conda-smithy bug?), and subsequent rerenderings did not restore those files..

**Pull request merged**
