### PR TITLE
re-add ppc64le build

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by inducer — APPROVED** [review]
If CI passes, I don't see a downside to doing this. @bryanwweber, it looks like you removed PPC. Any objections to adding it back?

**Comment by bryanwweber** [comment]
@inducer I only removed it because there were test failures I couldn't reproduce. If this resolves them, then no issues from my side

**Review by bryanwweber — APPROVED** [review]

**Comment by bryanwweber** [comment]
@matthiasdiener what's the difference between this and #21? Thanks 🙂

**Comment by matthiasdiener** [comment]
> @matthiasdiener what's the difference between this and #21? Thanks 🙂

#21 will attempt to fix issue #19, but it’s not ready yet.

**Comment by bryanwweber** [comment]
@matthiasdiener I _think_ it's necessary to avoid failing the other builds, since those already exist on the package server. Anyway, I'll merge once CI passes 👍

**Comment by matthiasdiener** [comment]
> @matthiasdiener I _think_ it's necessary to avoid failing the other builds, since those already exist on the package server. Anyway, I'll merge once CI passes 👍

Cool, thanks! I bumped the build number just in case.

**Pull request merged**
